# Generated by Django 4.2.17 on 2025-02-06 06:10

import accounts.models
import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired')], default='active', max_length=10)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=accounts.models.vendor_photo_path)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vendor/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='vendor/favicons/')),
                ('announcement', models.CharField(blank=True, max_length=200, null=True)),
                ('primary_color', colorfield.fields.ColorField(default='#007bff', image_field=None, max_length=25, samples=None)),
                ('secondary_color', colorfield.fields.ColorField(default='#6c757d', image_field=None, max_length=25, samples=None)),
                ('accent_color', colorfield.fields.ColorField(default='#28a745', image_field=None, max_length=25, samples=None)),
                ('heading_font', models.CharField(choices=[('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Poppins', 'Poppins'), ('Montserrat', 'Montserrat')], default='Roboto', max_length=50)),
                ('body_font', models.CharField(choices=[('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Poppins', 'Poppins'), ('Montserrat', 'Montserrat')], default='Open Sans', max_length=50)),
                ('store_name', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('about', models.TextField(blank=True)),
                ('popup_image', models.ImageField(blank=True, null=True, upload_to='vendor/popups/')),
                ('popup_title', models.CharField(blank=True, max_length=100)),
                ('popup_text', models.TextField(blank=True)),
                ('show_popup', models.BooleanField(default=False)),
                ('popup_delay', models.IntegerField(default=3, help_text='Delay in seconds before showing popup')),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, help_text='Support email address', max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, help_text='Support phone number', max_length=20, null=True)),
                ('contact_address', models.CharField(blank=True, help_text='Physical address', max_length=200, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=100)),
                ('meta_description', models.TextField(blank=True)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('profile_completion_date', models.DateTimeField(blank=True, null=True)),
                ('subdomain', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_subdomain_active', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('subdomain_request_date', models.DateTimeField(blank=True, null=True)),
                ('subdomain_approval_date', models.DateTimeField(blank=True, null=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Setting',
                'verbose_name_plural': 'Vendor Settings',
            },
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(upload_to=accounts.models.vendor_photo_path)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('business_name', models.CharField(max_length=100)),
                ('business_type', models.CharField(max_length=50)),
                ('pan_vat_number', models.CharField(max_length=50, unique=True)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('alternate_phone', models.CharField(blank=True, max_length=15)),
                ('alternate_email', models.EmailField(blank=True, max_length=254)),
                ('pan_vat_document', models.FileField(upload_to=accounts.models.vendor_document_path)),
                ('business_registration', models.FileField(upload_to=accounts.models.vendor_document_path)),
                ('citizenship_front', models.ImageField(upload_to=accounts.models.vendor_document_path)),
                ('citizenship_back', models.ImageField(upload_to=accounts.models.vendor_document_path)),
                ('citizenship_number', models.CharField(max_length=50, unique=True)),
                ('profile_status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_photos', models.ManyToManyField(blank=True, to='accounts.storephoto')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_vendorprofile',
            },
        ),
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(max_length=50, unique=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoverPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vendor/covers/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_photos', to='accounts.vendorsetting')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
