# Generated by Django 4.2.17 on 2025-02-06 06:16

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.vendor_photo_path),
        ),
    ]
