# Generated by Django 4.2.17 on 2025-02-06 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_vendorprofile_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='store_photos',
        ),
        migrations.AlterModelTable(
            name='storephoto',
            table='accounts_storephoto',
        ),
    ]
