# Generated by Django 4.2.17 on 2025-01-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_vendor_subdomain_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='subdomain',
            field=models.CharField(default='default-subdomain', max_length=50, unique=True),
        ),
    ]
