# Generated by Django 4.2.17 on 2025-01-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_vendor_subdomain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='subdomain',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
