# Generated by Django 4.2.17 on 2025-01-23 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_vendor_subdomain'),
    ]

    operations = [
    ]
