# Generated by Django 4.2.17 on 2025-01-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_update_subdomain_values'),
    ]

    operations = [
    ]
