# Generated by Django 4.2.17 on 2025-02-18 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customer_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('email', 'vendor')},
        ),
    ]
