# Generated by Django 4.2.17 on 2025-02-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customer_unique_together'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('email', 'vendor'), name='unique_customer_email_per_vendor'),
        ),
    ]
