# Generated by Django 4.2.17 on 2025-01-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_update_subdomain_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='subdomain',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
