# Generated by Django 4.2.17 on 2025-02-18 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customer_unique_customer_email_per_vendor'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='unique_customer_email_per_vendor',
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set(),
        ),
    ]
