# Generated by Django 4.2.17 on 2025-02-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_customer_unique_customer_email_per_vendor_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('email', 'vendor')},
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('email', 'vendor'), name='unique_customer_email_per_vendor'),
        ),
    ]
