# Generated by Django 4.2.17 on 2025-01-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_vendor_subdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='_is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
