# Generated by Django 4.2.17 on 2025-02-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_notification_link'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['vendor', '-created_at'], name='accounts_no_vendor__e0238f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['vendor', 'is_read'], name='accounts_no_vendor__25a486_idx'),
        ),
    ]
