# Generated by Django 4.2.17 on 2025-01-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_vendor_subdomain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='_is_staff',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='subdomain',
            field=models.CharField(default='default_subdomain', max_length=50, unique=True),
        ),
    ]
