# Generated by Django 4.2.17 on 2025-02-21 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_notification_accounts_no_vendor__e0238f_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='accounts_no_vendor__e0238f_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='accounts_no_vendor__25a486_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='link',
        ),
    ]
