# Generated by Django 4.2.17 on 2025-01-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_vendor__is_staff_alter_vendor_subdomain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='subdomain',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
