# Generated by Django 4.2.17 on 2025-01-23 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_vendor_subdomain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='subdomain',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
