# Generated by Django 4.2.17 on 2025-01-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_vendor_subdomain_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='subdomain',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
