# Generated by Django 4.2.17 on 2025-04-05 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_notification_action_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('general', 'General Notification'), ('order', 'Order Notification'), ('subdomain_request', 'Subdomain Request'), ('subdomain_update', 'Subdomain Update'), ('profile_update', 'Profile Update')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_vendor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
