# Generated by Django 4.2.17 on 2025-04-12 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_notification_is_admin_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_type', models.CharField(choices=[('new_arrivals', 'New Arrivals'), ('best_sellers', 'Best Sellers'), ('season_special', 'Season Special')], max_length=20)),
                ('image', models.ImageField(upload_to='vendor/collections/')),
                ('title', models.CharField(default='New Arrivals', max_length=100)),
                ('subtitle', models.CharField(default='Latest styles for you', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_images', to='accounts.vendorsetting')),
            ],
            options={
                'unique_together': {('vendor_setting', 'collection_type')},
            },
        ),
    ]
