# Generated by Django 4.2.17 on 2025-01-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_vendor_subdomain_subdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
