# Generated by Django 4.2.17 on 2025-01-24 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_vendor_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='is_staff',
        ),
    ]
