# Generated by Django 4.2.17 on 2025-01-24 19:39

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_vendor_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vendor/logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='vendor/covers/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='vendor/favicons/')),
                ('primary_color', colorfield.fields.ColorField(default='#007bff', image_field=None, max_length=25, samples=None)),
                ('secondary_color', colorfield.fields.ColorField(default='#6c757d', image_field=None, max_length=25, samples=None)),
                ('accent_color', colorfield.fields.ColorField(default='#28a745', image_field=None, max_length=25, samples=None)),
                ('heading_font', models.CharField(choices=[('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Poppins', 'Poppins'), ('Montserrat', 'Montserrat')], default='Roboto', max_length=50)),
                ('body_font', models.CharField(choices=[('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Poppins', 'Poppins'), ('Montserrat', 'Montserrat')], default='Open Sans', max_length=50)),
                ('store_name', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('about', models.TextField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=100)),
                ('meta_description', models.TextField(blank=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Setting',
                'verbose_name_plural': 'Vendor Settings',
            },
        ),
    ]
