# Generated by Django 4.2.17 on 2025-01-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_vendorsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vendor/covers/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='vendorsetting',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='vendorsetting',
            name='cover_photos',
            field=models.ManyToManyField(blank=True, to='accounts.coverphoto'),
        ),
    ]
