# Generated by Django 4.2.17 on 2025-01-24 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_coverphoto_remove_vendorsetting_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorsetting',
            name='cover_photos',
        ),
        migrations.AddField(
            model_name='coverphoto',
            name='vendor_setting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cover_photos', to='accounts.vendorsetting'),
            preserve_default=False,
        ),
    ]
