# Generated by Django 4.2.17 on 2025-01-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_vendorsetting_cover_photos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorsetting',
            name='announcement',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
