# Generated by Django 4.2.17 on 2025-01-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_vendorsetting_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorsetting',
            name='popup_delay',
            field=models.IntegerField(default=3, help_text='Delay in seconds before showing popup'),
        ),
        migrations.AddField(
            model_name='vendorsetting',
            name='popup_image',
            field=models.ImageField(blank=True, null=True, upload_to='vendor/popups/'),
        ),
        migrations.AddField(
            model_name='vendorsetting',
            name='popup_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorsetting',
            name='popup_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendorsetting',
            name='show_popup',
            field=models.BooleanField(default=False),
        ),
    ]
