# Generated by Django 4.2.17 on 2025-01-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_vendorsetting_popup_delay_vendorsetting_popup_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorsetting',
            name='contact_address',
            field=models.CharField(blank=True, help_text='Physical address', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendorsetting',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Support email address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='vendorsetting',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Support phone number', max_length=20, null=True),
        ),
    ]
