# Generated by Django 4.2.17 on 2025-02-05 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_storephoto_vendorsetting_vendorprofile_coverphoto'),
        ('accounts', '0025_vendorsetting_contact_address_and_more'),
    ]

    operations = [
    ]
