# Generated by Django 4.2.17 on 2025-02-08 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='colorvariant',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sizevariant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='colorvariant',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_colors', to='products.product'),
        ),
        migrations.AddField(
            model_name='sizevariant',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_sizes', to='products.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_variant',
            field=models.ManyToManyField(blank=True, related_name='variant_products', to='products.colorvariant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_variant',
            field=models.ManyToManyField(blank=True, related_name='variant_products', to='products.sizevariant'),
        ),
        migrations.AlterUniqueTogether(
            name='colorvariant',
            unique_together={('vendor', 'product', 'color_name')},
        ),
        migrations.AlterUniqueTogether(
            name='sizevariant',
            unique_together={('vendor', 'size_name', 'product')},
        ),
    ]
