# Generated by Django 4.2.17 on 2025-02-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_order_cancelled_at_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
